"""Dataset manifests: declaration, discovery, and module-level fetching.

Datasets are declared in TOML manifests. fwl-io ships one manifest for
datasets shared by several models (spectral files, multi-consumer lookup
tables); each model package may ship its own manifest for data only it
consumes and expose it through the ``fwl_io.manifests`` entry-point group.
Adding data to a model therefore never requires an fwl-io release.

Manifest schema, one table per dataset::

    [interior_lookup_tables.MgSiO3_Wolf_Bower_2018]
    name = "Wolf & Bower (2018) MgSiO3 equation of state"
    subdir = "interior_lookup_tables/MgSiO3_Wolf_Bower_2018"
    zenodo = "10.5281/zenodo.1234567"       # version DOI, never a concept DOI
    dataverse = "10.34894/ABCDEF"           # optional mirror
    required_by = ["aragog", "zalmoxis", "spider"]

Every dataset has a committed registry file next to the manifest, named
``<group>.<key>.registry.txt``, generated by ``fwl-io sync``. The registry
carries the file names and checksums; the manifest carries identity and
location. Version DOIs are pinned deliberately: a Zenodo concept DOI
resolves to the newest deposit and would let data drift underneath pinned
code, so ``fwl-io sync`` rejects concept DOIs.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from importlib.metadata import entry_points
from pathlib import Path

from fwl_io.registry import load_registry

_DOI_PREFIX = '10.'


@dataclass(frozen=True)
class Dataset:
    """A single downloadable dataset declared in a manifest."""

    key: str
    name: str
    subdir: str
    zenodo: str | None = None
    dataverse: str | None = None
    required_by: tuple[str, ...] = field(default_factory=tuple)
    registry_path: Path | None = None

    def registry(self) -> dict[str, str]:
        """Return the committed name-to-hash registry for this dataset."""
        if self.registry_path is None or not self.registry_path.is_file():
            raise FileNotFoundError(
                f'no registry file for dataset {self.key!r}; run: fwl-io sync <manifest>'
            )
        return load_registry(self.registry_path)


def _validate_doi(key: str, label: str, doi: str) -> None:
    if not doi.startswith(_DOI_PREFIX):
        raise ValueError(f'dataset {key!r}: {label} value {doi!r} is not a DOI')


def _walk_tables(tree: dict, prefix: str = '') -> list[tuple[str, dict]]:
    """Return (dotted-key, table) pairs for the leaf tables of a manifest."""
    leaves: list[tuple[str, dict]] = []
    for name, value in tree.items():
        if not isinstance(value, dict):
            continue
        dotted = f'{prefix}{name}'
        if any(isinstance(v, dict) for v in value.values()):
            leaves.extend(_walk_tables(value, prefix=f'{dotted}.'))
        else:
            leaves.append((dotted, value))
    return leaves


def load_manifest(path: str | Path) -> list[Dataset]:
    """Load and validate all datasets declared in one manifest file."""
    path = Path(path)
    with path.open('rb') as fh:
        tree = tomllib.load(fh)

    datasets: list[Dataset] = []
    for key, table in _walk_tables(tree):
        subdir = table.get('subdir')
        if not subdir:
            raise ValueError(f'dataset {key!r}: missing required field "subdir"')
        if Path(subdir).is_absolute():
            raise ValueError(f'dataset {key!r}: "subdir" must be relative to the data root')
        zenodo = table.get('zenodo')
        dataverse = table.get('dataverse')
        if not zenodo and not dataverse:
            raise ValueError(f'dataset {key!r}: at least one of "zenodo"/"dataverse" is required')
        if zenodo:
            _validate_doi(key, 'zenodo', zenodo)
        if dataverse:
            _validate_doi(key, 'dataverse', dataverse)
        datasets.append(
            Dataset(
                key=key,
                name=table.get('name', key),
                subdir=subdir,
                zenodo=zenodo,
                dataverse=dataverse,
                required_by=tuple(table.get('required_by', ())),
                registry_path=path.parent / f'{key}.registry.txt',
            )
        )
    return datasets


def shared_manifest_path() -> Path:
    """Entry-point target: the manifest of datasets shared across models."""
    return Path(__file__).parent / 'data' / 'shared_manifest.toml'


def discover_manifests() -> dict[str, list[Dataset]]:
    """Collect datasets from every installed ``fwl_io.manifests`` entry point.

    Returns a mapping from entry-point name (the providing package) to its
    datasets. Entry points must resolve to a zero-argument callable returning
    the manifest path.
    """
    found: dict[str, list[Dataset]] = {}
    for ep in entry_points(group='fwl_io.manifests'):
        manifest_path = ep.load()()
        found[ep.name] = load_manifest(manifest_path)
    return found


def fetch_for(module: str, data_root: str | Path | None = None) -> dict[str, list[Path]]:
    """Fetch every dataset a given model requires; return paths per dataset.

    Parameters
    ----------
    module : str
        Model name matched (case-insensitively) against ``required_by``.
    data_root : str | Path | None
        Override for the data root; defaults to the resolved FWL_DATA tree.
    """
    from fwl_io.fetch import create_fetcher

    module = module.lower()
    fetched: dict[str, list[Path]] = {}
    for datasets in discover_manifests().values():
        for ds in datasets:
            if module not in tuple(r.lower() for r in ds.required_by):
                continue
            fetcher = create_fetcher(
                subdir=ds.subdir,
                zenodo=ds.zenodo,
                dataverse=ds.dataverse,
                registry=ds.registry(),
                data_root=data_root,
            )
            fetched[ds.key] = [fetcher.fetch(name) for name in fetcher.registry]
    return fetched
