"""Dataset manifests: declaration, discovery, and model-level fetching.

Datasets are declared in TOML manifests. fwl-io ships one manifest for
datasets shared by several models (spectral files, multi-consumer lookup
tables); each model package may ship its own manifest for data only it
consumes and expose it through the ``fwl_io.manifests`` entry-point group.
Adding data to a model therefore never requires an fwl-io release.

Manifest schema, one table per dataset, identified by its ``zenodo`` key::

    manifest_schema = 1                     # optional, see below

    [interior.eos.wolf_bower_2018]
    name = "Wolf & Bower (2018) MgSiO3 equation of state"
    zenodo = "10.5281/zenodo.1234567"       # version DOI, never a concept DOI
    dataverse = "10.34894/ABCDEF"           # optional download mirror
    required_by = ["aragog", "zalmoxis", "spider"]
    extract = "tar"                         # optional: unpack a single-archive deposit

The optional root ``manifest_schema`` names the schema the file was written
against. Declaring it sharpens the diagnosis when something does not load: a
number above the schema the installed fwl-io implements can only mean the
reader is too old, and a number equal to it rules that reading out, so an
unknown field is reported as a misspelling alone.

The dotted table key is the dataset location below the data root: the table
above resolves into ``interior/eos/wolf_bower_2018``. Key segments are
restricted to letters, digits, ``_`` and ``-``, each starting with a letter,
digit or ``_``, so a key can neither escape the data root nor split into an
unintended path depth. A dataset resolves into ``<key-as-path>/r<record-id>``,
the version directory named for its Zenodo record.

A deposit packaged as one archive declares ``extract = "tar"`` or ``"zip"``; its
registry lists the archive, and the fetcher downloads and checksum-verifies it,
then extracts the members into the dataset directory (the archive is not kept).

Every dataset requires a Zenodo version DOI: the committed registry is
generated from the Zenodo record, so Dataverse is a download mirror, not an
alternative primary source. Version DOIs are pinned deliberately: a Zenodo
concept DOI resolves to the newest deposit and would let data drift
underneath pinned code, so ``fwl-io sync`` rejects concept DOIs.

Every dataset has a committed registry file next to the manifest, named
``<dotted-key>.registry.txt``, generated by ``fwl-io sync``. Packages that
ship their own manifest must ship the registry files with it (include both
in ``package-data``).
"""

from __future__ import annotations

import logging
import re
import tomllib
from dataclasses import dataclass, field
from importlib.metadata import entry_points
from pathlib import Path

from fwl_io.archive import ARCHIVE_KINDS
from fwl_io.doi import ZENODO_DOI_PATTERN, zenodo_record_id
from fwl_io.registry import load_registry

log = logging.getLogger(__name__)

# Re-exported so existing importers keep working; the parser lives in doi.
__all__ = [
    'Dataset',
    'ManifestSchemaError',
    'ZENODO_DOI_PATTERN',
    'discover_manifests',
    'fetch_for',
    'load_manifest',
    'shared_manifest_path',
    'zenodo_record_id',
]

_GENERIC_DOI_PATTERN = re.compile(r'(doi:)?10\.\S+')
_KEY_SEGMENT_PATTERN = re.compile(r'[A-Za-z0-9_][A-Za-z0-9_-]*')

# Every field a dataset table may declare. A manifest naming anything else is
# either a typo or written against a schema this fwl-io does not know.
_DATASET_FIELDS = frozenset({'name', 'zenodo', 'dataverse', 'required_by', 'extract'})

# The manifest schema this code implements, listed in the manifests
# documentation. Incremented whenever a manifest written for the previous
# number stops loading. It lives in the source rather than in packaging
# metadata, so it describes the code actually running, which an editable
# checkout's recorded version does not.
_MANIFEST_SCHEMA = 1

# The root key by which a manifest states the schema it was written against.
# Declaring it is optional and turns an ambiguous diagnosis into a definite
# one: a manifest that names a schema this code does not implement is from the
# future and says so, rather than being reported as a possible typo.
_SCHEMA_KEY = 'manifest_schema'


class ManifestSchemaError(ValueError):
    """A manifest and the installed fwl-io disagree about the manifest schema.

    Raised when a manifest declares something this fwl-io does not understand,
    something it no longer understands, or a field it reads only inside a
    dataset table. Subclasses ValueError, so callers that already handle a
    malformed manifest keep working.
    """


def _reading_version() -> str:
    """Describe the code reading the manifest, for use in an error message."""
    try:
        from fwl_io import __version__

        distribution = __version__
    except Exception:  # noqa: BLE001 -- a diagnostic must not raise
        distribution = 'unknown'
    return f'manifest schema {_MANIFEST_SCHEMA} (distribution {distribution})'


def _unknown_field_error(what: str, declared_schema: int | None = None) -> ManifestSchemaError:
    """Build the error for a field this fwl-io does not know.

    Without a declared schema both readings are offered, because both are
    common: a misspelt field, and a manifest written against a schema newer
    than the fwl-io reading it. A manifest declaring the schema this code
    implements has ruled the second reading out, so the message names the typo
    alone. A manifest declaring an older schema does not: the schema number
    rises whenever a manifest written for the previous one stops loading, so a
    field this code does not know may be one that older schema had and this
    one dropped, and both readings stay on the table.
    """
    if declared_schema == _MANIFEST_SCHEMA:
        return ManifestSchemaError(
            f'{what}. The manifest declares {_SCHEMA_KEY} {declared_schema}, the schema '
            f'this fwl-io implements, so the field is misspelt rather than newer than '
            f'this code.'
        )
    return ManifestSchemaError(
        f'{what}. This fwl-io reads {_reading_version()}: check the spelling, or '
        f'upgrade fwl-io if the manifest was written against a newer schema.'
    )


def _read_declared_schema(tree: dict) -> int | None:
    """Return the schema a manifest declares at its root, if it declares one.

    Raises when the manifest names a schema this code does not implement,
    which is the case the key exists to make unambiguous, and when the value
    is not a schema number at all.
    """
    if _SCHEMA_KEY not in tree:
        return None
    declared = tree[_SCHEMA_KEY]
    # A table of this name is a directory level like any other, the same rule
    # `subdir` follows: the reserved name applies to the scalar, not to a
    # dataset an author happens to have called this. Leave it to the walk.
    if isinstance(declared, dict) or (
        isinstance(declared, list) and any(isinstance(item, dict) for item in declared)
    ):
        return None
    # bool is an int subclass, and `manifest_schema = true` is a mistake worth
    # naming rather than reading as schema 1.
    if isinstance(declared, bool) or not isinstance(declared, int) or declared < 1:
        raise ManifestSchemaError(
            f'the manifest root declares {_SCHEMA_KEY} {declared!r}; it must be a whole '
            f'number of at least 1, naming the manifest schema the file was written '
            f'against.'
        )
    if declared > _MANIFEST_SCHEMA:
        raise ManifestSchemaError(
            f'the manifest declares {_SCHEMA_KEY} {declared}, but this fwl-io reads '
            f'{_reading_version()}: upgrade fwl-io to read this manifest.'
        )
    return declared


def _misplaced_schema_error(what: str) -> ManifestSchemaError:
    """Build the error for the reserved schema key written below the root.

    The name is spelt correctly and sits at the wrong level, so reporting it as
    an unknown field would give the one reading that is certainly wrong.
    """
    return ManifestSchemaError(
        f'{what}. {_SCHEMA_KEY!r} is a manifest-root key naming the schema the file was '
        f'written against: move the line above the first table.'
    )


def _misplaced_field_error(what: str) -> ManifestSchemaError:
    """Build the error for a known field declared outside a dataset table."""
    return ManifestSchemaError(
        f'{what}. This fwl-io reads {_reading_version()}, in which it is a dataset '
        f'field: move the line into the dataset table, the one carrying the '
        f'"zenodo" pin.'
    )


def _dropped_field_error(what: str) -> ManifestSchemaError:
    """Build the error for a field this fwl-io no longer reads."""
    return ManifestSchemaError(
        f'{what}. This fwl-io reads {_reading_version()}, which no longer takes '
        f'that field: remove the line.'
    )


@dataclass(frozen=True, kw_only=True)
class Dataset:
    """A single downloadable dataset declared in a manifest."""

    key: str
    name: str
    zenodo: str | None = None
    dataverse: str | None = None
    required_by: tuple[str, ...] = field(default_factory=tuple)
    registry_path: Path | None = None
    extract: str | None = None

    @property
    def subdir(self) -> str:
        """Dataset location below the data root, derived from the dotted key."""
        return self.key.replace('.', '/')

    def registry(self) -> dict[str, str]:
        """Return the committed name-to-hash registry for this dataset."""
        if self.registry_path is None or not self.registry_path.is_file():
            raise FileNotFoundError(
                f'no registry file for dataset {self.key!r}; run: fwl-io sync <manifest>'
            )
        return load_registry(self.registry_path)


def _validate_key_segment(segment: str, parent: str) -> None:
    """Reject a table name that cannot serve as one directory level."""
    where = f'under {parent!r}' if parent else 'at the top level of the manifest'
    if segment in ('.', '..'):
        raise ValueError(
            f'table segment {segment!r} {where} is a relative-path component, not a '
            f'directory name; the dataset location is derived from the key'
        )
    if not _KEY_SEGMENT_PATTERN.fullmatch(segment):
        raise ValueError(
            f'table segment {segment!r} {where} is not a valid directory name '
            f'(letters, digits, "_" and "-", starting with a letter, digit or "_"); '
            f'the dataset location is derived from the key'
        )


def _reject_declared_subdir(where: str, table: dict, derived: str | None = None) -> None:
    """Refuse a location declared alongside the key that already carries it.

    A sub-table shares the mapping with the scalar fields, so a group named
    ``subdir`` is a directory name like any other and is left to the walk,
    in either the single-table or the array-of-tables spelling.
    """
    declared = table.get('subdir')
    if declared is None or isinstance(declared, dict):
        return
    if isinstance(declared, list) and any(isinstance(item, dict) for item in declared):
        return
    location = (
        f'the location is derived from the table key, here {derived!r}'
        if derived
        else 'a dataset location is derived from its own table key'
    )
    raise _dropped_field_error(
        f'{where}: "subdir" is not a manifest field; {location} '
        f'(create_fetcher() still takes a subdir argument, manifests do not)'
    )


def _walk_tables(
    tree: dict, prefix: str = '', declared_schema: int | None = None
) -> list[tuple[str, dict]]:
    """Return (dotted-key, table) pairs for the dataset tables of a manifest.

    A table is a dataset when it carries the ``zenodo`` key. Grouping tables
    (no ``zenodo``) are recursed into. Ambiguous structures are rejected
    instead of silently reinterpreted.
    """
    leaves: list[tuple[str, dict]] = []
    for name, value in tree.items():
        if isinstance(value, list) and any(isinstance(item, dict) for item in value):
            raise ValueError(
                f'{prefix}{name}: arrays of tables ([[...]]) are not supported in manifests'
            )
        if not isinstance(value, dict):
            if name in _DATASET_FIELDS:
                where = (
                    f'grouping table {prefix.rstrip(".")!r} declares {name!r}'
                    if prefix
                    else f'the manifest root declares {name!r}'
                )
                raise _misplaced_field_error(where)
            if prefix:
                if name == _SCHEMA_KEY:
                    raise _misplaced_schema_error(
                        f'grouping table {prefix.rstrip(".")!r} declares {name!r}'
                    )
                raise _unknown_field_error(
                    f'grouping table {prefix.rstrip(".")!r} declares {name!r}, and a '
                    f'grouping level takes no fields',
                    declared_schema,
                )
            # A root scalar that names no dataset field is a manifest's own
            # setting. The schema declaration is one of those, already read
            # and validated before the walk began.
            continue
        dotted = f'{prefix}{name}'
        _validate_key_segment(name, prefix.rstrip('.'))
        _reject_declared_subdir(f'table {dotted!r}', value, dotted.replace('.', '/'))
        for child, child_value in value.items():
            if isinstance(child_value, list) and any(isinstance(i, dict) for i in child_value):
                raise ValueError(
                    f'{dotted}.{child}: arrays of tables ([[...]]) are not supported in manifests'
                )
        has_subtables = any(isinstance(v, dict) for v in value.values())
        if 'zenodo' in value:
            if has_subtables:
                raise ValueError(f'dataset {dotted!r}: dataset tables must not contain sub-tables')
            unknown = sorted(set(value) - _DATASET_FIELDS)
            if _SCHEMA_KEY in unknown:
                raise _misplaced_schema_error(f'dataset {dotted!r} declares {_SCHEMA_KEY!r}')
            if unknown:
                raise _unknown_field_error(
                    f'dataset {dotted!r} declares {", ".join(repr(f) for f in unknown)}, '
                    f'which is not a dataset field '
                    f'(known fields: {", ".join(sorted(_DATASET_FIELDS))})',
                    declared_schema,
                )
            leaves.append((dotted, value))
        elif has_subtables:
            leaves.extend(_walk_tables(value, prefix=f'{dotted}.', declared_schema=declared_schema))
        else:
            raise ValueError(
                f'table {dotted!r} has no "zenodo" key, so it is neither a dataset nor a '
                f'grouping level; a Zenodo version DOI is required for every dataset '
                f'("dataverse" is a download mirror, not a primary source)'
            )
    return leaves


def load_manifest(path: str | Path) -> list[Dataset]:
    """Load and validate all datasets declared in one manifest file."""
    path = Path(path)
    with path.open('rb') as fh:
        tree = tomllib.load(fh)

    # Read the declaration first: a manifest above this code's schema cannot be
    # judged by this code's rules, so it must be refused before they are applied.
    declared_schema = _read_declared_schema(tree)
    _reject_declared_subdir('the manifest root', tree)
    datasets: list[Dataset] = []
    folded: dict[str, str] = {}
    for key, table in _walk_tables(tree, declared_schema=declared_schema):
        clash = folded.setdefault(key.lower(), key)
        if clash != key:
            raise ValueError(
                f'datasets {clash!r} and {key!r} differ only in case; they would share one '
                f'directory and one registry file on a case-insensitive filesystem'
            )
        zenodo = table.get('zenodo')
        dataverse = table.get('dataverse')
        if zenodo == '':
            raise ValueError(
                f'dataset {key!r}: the "zenodo" value is empty; a Zenodo version DOI is '
                f'required ("dataverse" is a download mirror, not a primary source)'
            )
        if not isinstance(zenodo, str) or not ZENODO_DOI_PATTERN.fullmatch(zenodo):
            raise ValueError(
                f'dataset {key!r}: zenodo value {zenodo!r} is not a Zenodo DOI '
                f'of the form 10.5281/zenodo.<record-id>'
            )
        if dataverse is not None and (
            not isinstance(dataverse, str) or not _GENERIC_DOI_PATTERN.fullmatch(dataverse)
        ):
            raise ValueError(f'dataset {key!r}: dataverse value {dataverse!r} is not a DOI')
        name = table.get('name', key)
        if not isinstance(name, str) or not name.strip():
            raise ValueError(f'dataset {key!r}: "name" must be non-empty text, got {name!r}')
        required_by = table.get('required_by', ())
        if not isinstance(required_by, list | tuple) or not all(
            isinstance(model, str) for model in required_by
        ):
            raise ValueError(
                f'dataset {key!r}: "required_by" must be a list of model names, got {required_by!r}'
            )
        extract = table.get('extract')
        if extract is not None and extract not in ARCHIVE_KINDS:
            raise ValueError(
                f'dataset {key!r}: extract value {extract!r} must be one of {ARCHIVE_KINDS}'
            )
        datasets.append(
            Dataset(
                key=key,
                name=name,
                zenodo=zenodo,
                dataverse=dataverse,
                required_by=tuple(required_by),
                registry_path=path.parent / f'{key}.registry.txt',
                extract=extract,
            )
        )
    return datasets


def shared_manifest_path() -> Path:
    """Entry-point target: the manifest of datasets shared across models."""
    return Path(__file__).parent / 'data' / 'shared_manifest.toml'


def _discover() -> tuple[dict[str, list[Dataset]], dict[str, str]]:
    """Load every installed manifest; return (datasets per provider, errors)."""
    found: dict[str, list[Dataset]] = {}
    errors: dict[str, str] = {}
    for ep in entry_points(group='fwl_io.manifests'):
        try:
            manifest_path = ep.load()()
            found[ep.name] = load_manifest(manifest_path)
        except Exception as exc:  # noqa: BLE001 -- one bad provider must not break the rest
            errors[ep.name] = str(exc)
            log.warning('skipping manifest provider %r: %s', ep.name, exc)
    return found, errors


def discover_manifests() -> dict[str, list[Dataset]]:
    """Collect datasets from every installed ``fwl_io.manifests`` entry point.

    Entry points must resolve to a zero-argument callable returning the
    manifest path. A provider whose manifest fails to load is skipped with a
    logged warning, so one broken package cannot break data access for every
    other model.
    """
    found, _ = _discover()
    return found


def fetch_for(model: str, data_root: str | Path | None = None) -> dict[str, list[Path]]:
    """Fetch every dataset a given model requires; return paths per dataset.

    All matching datasets are attempted; failures are collected and raised
    together at the end so one broken dataset does not block the others
    (files fetched before the error remain in place).

    An unreadable manifest counts as a failure here, even when other datasets
    arrived: a manifest that cannot be parsed may be the one declaring this
    model, and a model is routinely served by both its own manifest and the
    shared one. Listing is more forgiving, since it reports per provider and
    a reader can see which one is missing.

    Parameters
    ----------
    model : str
        Model name matched (case-insensitively) against ``required_by``.
    data_root : str | Path | None
        Override for the data root; defaults to the resolved FWL_DATA tree.
    """
    from fwl_io.fetch import create_fetcher

    model = model.lower()
    fetched: dict[str, list[Path]] = {}
    failures: dict[str, str] = {}
    providers, provider_errors = _discover()
    for datasets in providers.values():
        for ds in datasets:
            if model not in tuple(r.lower() for r in ds.required_by):
                continue
            try:
                fetcher = create_fetcher(
                    subdir=ds.subdir,
                    zenodo=ds.zenodo,
                    dataverse=ds.dataverse,
                    registry=ds.registry(),
                    data_root=data_root,
                    extract=ds.extract,
                )
                fetched[ds.key] = fetcher.fetch_all()
            except Exception as exc:  # noqa: BLE001 -- aggregate and re-raise below
                failures[ds.key] = str(exc)
    if failures or provider_errors:
        report = [f'fetching data for model {model!r} failed ({len(fetched)} dataset(s) arrived)']
        if failures:
            report.append(f'{len(failures)} dataset(s) failed:')
            report += [f'  {key}: {msg}' for key, msg in sorted(failures.items())]
        if provider_errors:
            report.append(f'{len(provider_errors)} manifest(s) could not be read:')
            report += [f'  {name}: {msg}' for name, msg in sorted(provider_errors.items())]
        raise RuntimeError('\n'.join(report))
    return fetched
