"""Dataset manifests: declaration, discovery, and module-level fetching.

Datasets are declared in TOML manifests. fwl-io ships one manifest for
datasets shared by several models (spectral files, multi-consumer lookup
tables); each model package may ship its own manifest for data only it
consumes and expose it through the ``fwl_io.manifests`` entry-point group.
Adding data to a model therefore never requires an fwl-io release.

Manifest schema, one table per dataset, identified by its ``subdir`` key::

    [interior_lookup_tables.MgSiO3_Wolf_Bower_2018]
    name = "Wolf & Bower (2018) MgSiO3 equation of state"
    subdir = "interior_lookup_tables/MgSiO3_Wolf_Bower_2018"
    zenodo = "10.5281/zenodo.1234567"       # version DOI, never a concept DOI
    dataverse = "10.34894/ABCDEF"           # optional download mirror
    required_by = ["aragog", "zalmoxis", "spider"]

Every dataset requires a Zenodo version DOI: the committed registry is
generated from the Zenodo record, so Dataverse is a download mirror, not an
alternative primary source. Version DOIs are pinned deliberately: a Zenodo
concept DOI resolves to the newest deposit and would let data drift
underneath pinned code, so ``fwl-io sync`` rejects concept DOIs.

Every dataset has a committed registry file next to the manifest, named
``<group>.<key>.registry.txt``, generated by ``fwl-io sync``. Packages that
ship their own manifest must ship the registry files with it (include both
in ``package-data``).
"""

from __future__ import annotations

import logging
import re
import tomllib
from dataclasses import dataclass, field
from importlib.metadata import entry_points
from pathlib import Path

from fwl_io.registry import load_registry

log = logging.getLogger(__name__)

ZENODO_DOI_PATTERN = re.compile(r'^(doi:)?10\.5281/zenodo\.(\d+)$')
_GENERIC_DOI_PATTERN = re.compile(r'^(doi:)?10\.\S+$')


@dataclass(frozen=True)
class Dataset:
    """A single downloadable dataset declared in a manifest."""

    key: str
    name: str
    subdir: str
    zenodo: str | None = None
    dataverse: str | None = None
    required_by: tuple[str, ...] = field(default_factory=tuple)
    registry_path: Path | None = None

    def registry(self) -> dict[str, str]:
        """Return the committed name-to-hash registry for this dataset."""
        if self.registry_path is None or not self.registry_path.is_file():
            raise FileNotFoundError(
                f'no registry file for dataset {self.key!r}; run: fwl-io sync <manifest>'
            )
        return load_registry(self.registry_path)


def _validate_subdir(key: str, subdir: str) -> None:
    if '\\' in subdir:
        raise ValueError(f'dataset {key!r}: "subdir" contains a backslash')
    path = Path(subdir)
    if path.is_absolute():
        raise ValueError(f'dataset {key!r}: "subdir" must be relative to the data root')
    if '..' in path.parts:
        raise ValueError(f'dataset {key!r}: "subdir" contains a ".." component')


def _walk_tables(tree: dict, prefix: str = '') -> list[tuple[str, dict]]:
    """Return (dotted-key, table) pairs for the dataset tables of a manifest.

    A table is a dataset when it carries the ``subdir`` key. Grouping tables
    (no ``subdir``) are recursed into. Ambiguous structures are rejected
    instead of silently reinterpreted.
    """
    leaves: list[tuple[str, dict]] = []
    for name, value in tree.items():
        if isinstance(value, list) and any(isinstance(item, dict) for item in value):
            raise ValueError(
                f'{prefix}{name}: arrays of tables ([[...]]) are not supported in manifests'
            )
        if not isinstance(value, dict):
            continue
        dotted = f'{prefix}{name}'
        for child, child_value in value.items():
            if isinstance(child_value, list) and any(isinstance(i, dict) for i in child_value):
                raise ValueError(
                    f'{dotted}.{child}: arrays of tables ([[...]]) are not supported in manifests'
                )
        has_subtables = any(isinstance(v, dict) for v in value.values())
        if 'subdir' in value:
            if has_subtables:
                raise ValueError(f'dataset {dotted!r}: dataset tables must not contain sub-tables')
            leaves.append((dotted, value))
        elif has_subtables:
            leaves.extend(_walk_tables(value, prefix=f'{dotted}.'))
        else:
            raise ValueError(f'dataset {dotted!r}: missing required field "subdir"')
    return leaves


def load_manifest(path: str | Path) -> list[Dataset]:
    """Load and validate all datasets declared in one manifest file."""
    path = Path(path)
    with path.open('rb') as fh:
        tree = tomllib.load(fh)

    datasets: list[Dataset] = []
    for key, table in _walk_tables(tree):
        subdir = table['subdir']
        _validate_subdir(key, subdir)
        zenodo = table.get('zenodo')
        dataverse = table.get('dataverse')
        if not zenodo:
            raise ValueError(
                f'dataset {key!r}: a Zenodo version DOI is required '
                f'("dataverse" is a download mirror, not a primary source)'
            )
        if not ZENODO_DOI_PATTERN.match(zenodo):
            raise ValueError(
                f'dataset {key!r}: zenodo value {zenodo!r} is not a Zenodo DOI '
                f'of the form 10.5281/zenodo.<record-id>'
            )
        if dataverse and not _GENERIC_DOI_PATTERN.match(dataverse):
            raise ValueError(f'dataset {key!r}: dataverse value {dataverse!r} is not a DOI')
        datasets.append(
            Dataset(
                key=key,
                name=table.get('name', key),
                subdir=subdir,
                zenodo=zenodo,
                dataverse=dataverse,
                required_by=tuple(table.get('required_by', ())),
                registry_path=path.parent / f'{key}.registry.txt',
            )
        )
    return datasets


def shared_manifest_path() -> Path:
    """Entry-point target: the manifest of datasets shared across models."""
    return Path(__file__).parent / 'data' / 'shared_manifest.toml'


def _discover() -> tuple[dict[str, list[Dataset]], dict[str, str]]:
    """Load every installed manifest; return (datasets per provider, errors)."""
    found: dict[str, list[Dataset]] = {}
    errors: dict[str, str] = {}
    for ep in entry_points(group='fwl_io.manifests'):
        try:
            manifest_path = ep.load()()
            found[ep.name] = load_manifest(manifest_path)
        except Exception as exc:  # noqa: BLE001 -- one bad provider must not break the rest
            errors[ep.name] = str(exc)
            log.warning('skipping manifest provider %r: %s', ep.name, exc)
    return found, errors


def discover_manifests() -> dict[str, list[Dataset]]:
    """Collect datasets from every installed ``fwl_io.manifests`` entry point.

    Entry points must resolve to a zero-argument callable returning the
    manifest path. A provider whose manifest fails to load is skipped with a
    logged warning, so one broken package cannot break data access for every
    other model.
    """
    found, _ = _discover()
    return found


def fetch_for(module: str, data_root: str | Path | None = None) -> dict[str, list[Path]]:
    """Fetch every dataset a given model requires; return paths per dataset.

    All matching datasets are attempted; failures are collected and raised
    together at the end so one broken dataset does not block the others
    (files fetched before the error remain in place).

    Parameters
    ----------
    module : str
        Model name matched (case-insensitively) against ``required_by``.
    data_root : str | Path | None
        Override for the data root; defaults to the resolved FWL_DATA tree.
    """
    from fwl_io.fetch import create_fetcher

    module = module.lower()
    fetched: dict[str, list[Path]] = {}
    failures: dict[str, str] = {}
    for datasets in discover_manifests().values():
        for ds in datasets:
            if module not in tuple(r.lower() for r in ds.required_by):
                continue
            try:
                fetcher = create_fetcher(
                    subdir=ds.subdir,
                    zenodo=ds.zenodo,
                    dataverse=ds.dataverse,
                    registry=ds.registry(),
                    data_root=data_root,
                )
                fetched[ds.key] = fetcher.fetch_all()
            except Exception as exc:  # noqa: BLE001 -- aggregate and re-raise below
                failures[ds.key] = str(exc)
    if failures:
        detail = '\n'.join(f'  {key}: {msg}' for key, msg in sorted(failures.items()))
        raise RuntimeError(
            f'{len(failures)} dataset(s) failed for module {module!r} '
            f'({len(fetched)} succeeded):\n{detail}'
        )
    return fetched
